server:
  port: ${vcap.application.port:8590}
  
management:
  context-path: /configpropertiesserver
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /configpropertiesserver/info
    healthCheckUrlPath: /configpropertiesserver/health  

#conf: /your/local/path/local-configuration		#Define this in case you need to test local properties configuration

#in our case we decided to integrate our server configuration with properties defined at git server
spring:
  cloud:
    config:
      server:
        git:
          uri: ${conf:https://github.com/davisusanibar/netflixoss-all-tour-config}		#git project that give to the app global properties configuration 
          basedir: target/config

security:
  user:
    name: adminuser
    password: "{cipher}AQAc9OSnvjINdppzekVwaOXVVedkKbCkCdNgQzW3ltj4qbql8HoevCH0/VWZdjpdVTqiYKq8gjm62Kne2o16jiVosG/PyhDMeAMh0Z411ZK5jVtY40TPI+dTNHBYbqmNffF/cFArRBvVa5+tt9LP0N8khbpML7OHJ0s/S932S+rgHN36cAsIN4FwpVdJgOeb4R0ahZnv7YUD9KbPh+KsYPQGNbeXLGIGz3b5W8hj0IV1OzSovTFlqjgAvf292XTD/LuXNoJ8cvzmVQqzdpDOSXG1IwJ5KWgq+PXiRHCul1Q5yF+xRyB46T3DRsfxKq0im+E1U1LN1HGJ9Vulss2Ck1lHl26LmJrbCSqeQtBVoDg6JelWSmQO48FY9h2vMKrCKv0="          
